#! /bin/sh

sxhkd &
polybar top &

bspc monitor -d DVI-D-0 I II III
bspc monitor -d DVI-I-1 IV V VI VII
bspc monitor -d HDMI-0 VIII IX X

#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Opera desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#if [ "$(command -v compton 2> /dev/null)" ]; then
#	compton --config "$HOME/.config/compton/compton.conf" &
#fi

xcompmgr -C -t-5 -l-5 .r4.2 .o.55 &

